# make file to build this lib
all:
	cc -Wall -Wextra -Werror main_andrei.c libunit.c my_f/my_f.c my_f/tests/00_my_f_tests_launcher.c my_f/tests/01_my_f_test_ok.c my_f/tests/02_my_f_test_ko.c my_f/tests/03_my_f_test_sigsegv.c -o libunit_main
